
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: khringproj_root_password
      MYSQL_DATABASE: khringproj
      MYSQL_USER: khringproj_user
      MYSQL_PASSWORD: khringproj_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - khringproj_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_ui
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: khringproj_root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - khringproj_network

volumes:
  mysql_data:

networks:
  khringproj_network: