services:
  mysql:
    image: mysql:8.0
    container_name: khringproj-mysql-1
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - khringproj_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: khringproj-phpmyadmin-1
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - khringproj_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  khringproj_network:
    driver: bridge